// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD50ygnK4vI5rQIxQI18pQa2Wk6iiJWPWs',
    appId: '1:479855469765:web:d15a5c5efc900ab2457cac',
    messagingSenderId: '479855469765',
    projectId: 'fitapp-27861',
    authDomain: 'fitapp-27861.firebaseapp.com',
    storageBucket: 'fitapp-27861.firebasestorage.app',
    measurementId: 'G-Z735EHJY3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcnIX86_XkR_14tp_UL_vGA6nAFE6NMMk',
    appId: '1:479855469765:android:dd5a283cd7d079d2457cac',
    messagingSenderId: '479855469765',
    projectId: 'fitapp-27861',
    storageBucket: 'fitapp-27861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCFhFdlEU__Ljm2Qa2IJm6INziuLGRfQI',
    appId: '1:479855469765:ios:3d5783b85706ffb7457cac',
    messagingSenderId: '479855469765',
    projectId: 'fitapp-27861',
    storageBucket: 'fitapp-27861.firebasestorage.app',
    iosBundleId: 'com.example.fitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCFhFdlEU__Ljm2Qa2IJm6INziuLGRfQI',
    appId: '1:479855469765:ios:3d5783b85706ffb7457cac',
    messagingSenderId: '479855469765',
    projectId: 'fitapp-27861',
    storageBucket: 'fitapp-27861.firebasestorage.app',
    iosBundleId: 'com.example.fitapp',
  );
}
